class Autogenerated {
  String? soHieuTau;
  int? chuyenBien;
  List<DanhSachMeCa>? danhSachMeCa;

  Autogenerated({this.soHieuTau, this.chuyenBien, this.danhSachMeCa});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    soHieuTau = json['so_hieu_tau'];
    chuyenBien = json['chuyen_bien'];
    if (json['danh_sach_me_ca'] != null) {
      danhSachMeCa = <DanhSachMeCa>[];
      json['danh_sach_me_ca'].forEach((v) {
        danhSachMeCa!.add(new DanhSachMeCa.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['so_hieu_tau'] = this.soHieuTau;
    data['chuyen_bien'] = this.chuyenBien;
    if (this.danhSachMeCa != null) {
      data['danh_sach_me_ca'] =
          this.danhSachMeCa!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DanhSachMeCa {
  int? meCa;
  List<DuLieuMeCa>? duLieuMeCa;

  DanhSachMeCa({this.meCa, this.duLieuMeCa});

  DanhSachMeCa.fromJson(Map<String, dynamic> json) {
    meCa = json['me_ca'];
    if (json['du_lieu_me_ca'] != null) {
      duLieuMeCa = <DuLieuMeCa>[];
      json['du_lieu_me_ca'].forEach((v) {
        duLieuMeCa!.add(new DuLieuMeCa.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['me_ca'] = this.meCa;
    if (this.duLieuMeCa != null) {
      data['du_lieu_me_ca'] = this.duLieuMeCa!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class DuLieuMeCa {
  String? tenLoaiCa;
  int? khoiLuong;

  DuLieuMeCa({this.tenLoaiCa, this.khoiLuong});

  DuLieuMeCa.fromJson(Map<String, dynamic> json) {
    tenLoaiCa = json['ten_loai_ca'];
    khoiLuong = json['khoi_luong'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['ten_loai_ca'] = this.tenLoaiCa;
    data['khoi_luong'] = this.khoiLuong;
    return data;
  }
}
